import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./component/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MultChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex  flex-row w-full h-full min-h-screen bg-[#F2F2F2]">
          <div className="w-[15%] h-full min-h-screen bg-[#F8F9FA]">SideBar</div>
          <div className="w-[85%] h-full min-h-screen">
            <NavBar />
            <div className="absolute">
            {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
