import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./component/NavBar";
import SideBar from "./component/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MultChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-[#F2F2F2]">
        <div className="flex  flex-row w-full h-[100%] min-h-full max-h-full bg-[#F2F2F2]">
          <div className="w-[15%] h-[100%] min-h-full max-h-full bg-[#F8F9FA]">
            <SideBar />
          </div>
          <div className="w-[85%] h-full min-h-full max-h-full bg-[#F2F2F2]">
            <NavBar />
            <div className="absolute w-[75%] h-full min-h-full">
            {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
